### ISSUE TITLE
Make the model class better

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/jsontableschema-py#34]
* Consistency in naming and access (data vs meta data, etc.)
* Data methods ( https://github.com/okfn/jsontableschema-py/blob/master/jsontableschema/model.py#L186-L221 ) should use `tabulator-py`

**Comment by pwalsh** [comment]
As mentioned in comments in #51 data methods should break out into a `Resource` class, and then tighten up `SchemaModel`.

**Comment by roll** [comment]
I think we should to think about all `breaking changes` could be needed (also https://github.com/datapackages/jsontableschema-py/issues/50 and ?) and to release it in one version `0.7.0` for example.

Or `SchemaModel` refactoring could be non breaking?

**Comment by pwalsh** [comment]
@roll I think it would be breaking. The data methods added there a few months back would be removed in favor of a `Resource` class. The schema-related methods and properties could likely stay as they are, unless you see any particular issue there. WDYT?

**Comment by pwalsh** [comment]
And yes, agree to release in single version. It is good, I think, to do this now as work is starting on an R lib, as well as further work on the Javascript lib, and this code will serve as a reference.

**Comment by roll** [comment]
Of course I'm +1 for `breaking` (if we could do this) because It will let to have much cleaner interface.

**Comment by roll** [comment]
It's interesting - could `Resource` implemented in `jsontableschema-py`be reused in `datapackage-py`?

**Comment by pwalsh** [comment]
I guess the problem is that `Resource` there needs to be more generic, where as here it is definitely a *tabular* `Resource`.

**Comment by vitorbaptista** [comment]
There's both a `Resource` and a `TabularResource` class in `datapackage-py`. Depending on what methods are implemented here, we could reuse something in `datapackage-py`. For the actual class definition, I'd rather keep it in `datapackage-py` to keep a layer of separation that allows `jsontableschema-py` to evolve independently of `datapackage-py`.

**Comment by roll** [comment]
About breaking changes - there is an other way - to keep some time deprecated `jsontableshema.model.ShemaModel` (if there are many users using it) and expose new `jsontableschema.Model` and `jsontableshema.Resource` api for example.

**Comment by vitorbaptista** [comment]
I wouldn't bother much with breaking changes, just document them and bump the version number. Following semantic versioning, versions before 1.0.0 don't need to maintain compatibility.

**Comment by pwalsh** [comment]
@vitorbaptista @roll @zhenyab @rgrp 

Ok. Somewhat based on [datapackage.Resource](https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/resource.py) in the Python Data Package lib, I'm suggesting we implement the following for `jsontableschema.Resource` (we will likely implement it in js lib now, and add here soon):

```
class Resource(object):

    def __init__(self, data, schema):
        self.stream = self._get_stream(data) // uses tabulator. data could be a path, a url or a stream already
        self.schema = self._get_schema(schema) // uses the model.Schema, but could already be an instance of
        self.descriptor = self._make_descriptor() // makes a basic, DataPackage-compatible Resource descriptor for this Resource

    def __iter__(self):
        // iterate over data, yielding arrays of cast values
```

There are probably other handy things `Resource` could have, but this would be enough to provide great value IMHO.

As for the current `SchemaModel` class, we'd likely leave the data handling methods that are there (`cast`, `convert_row`, and `convert`), possibly removing `convert` (?), as they are lower level and not necessarily tied to the `Resource` concept. They will likely be used directly by `Resource` for its casting.

Comments, suggestions? we want to implement this in the js lib "now" :).

**Comment by roll** [comment]
I think we could to start from minimum possible interface interface based on `datapackage.Resource` like: 
```
Resource(schema, data)
  schema
  data
  iter()
```
Then when we all be able to fully contribute here we could extend functionality. For example as I've written here I see it's possible to have `Resourse` working transparently using streams with any kind of data source like tabulator source, sql storage etc.

**Comment by pwalsh** [comment]
@roll ok. That is essentially what I am saying too (except I see order of `schema`, `data`). But curious why are we using `iter` and not `__iter__`?

**Comment by roll** [comment]
@pwalsh 
about order - https://github.com/frictionlessdata/jsontableschema-py#pushpull - and the same for `datapackage`

About `iter()` - I'm curious too) (cc @vitorbaptista) But I think it was a good decision - explicit and could be used across languages.

**Comment by pwalsh** [comment]
@roll good. BTW I guess that once we have this `Resource`, we will like add `push` `pull` on it, but we'll get to that after a simple implementation now. thanks.

**Comment by roll** [comment]
@pwalsh 
Yea `Storage` integration could be interesting =)

**Comment by pwalsh** [comment]
@roll left here is:

- do we employ tabulator for the data methods?
- sync the naming to the recent improvements in the js version of the lib

Any other discussion here moves to #78 i guess.

**Comment by roll** [comment]
Removing breaking because we implement it as `Schema` and deprecate `model.SchemaModel` (without removing it for now).
