### ISSUE TITLE
`required` constraint is not implemented

### ISSUE THREAD

**Issue by akariv** [frictionlessdata/jsontableschema-py#53]
Looks like this constraint wasn't implemented.

(this is just from looking at the code, so I might have missed it..)

**Comment by roll** [comment]
@akariv could you please provide an use case example?

**Comment by akariv** [comment]
The simplest use case would be this simple CSV file:
```
numeric_field

```
(notice the empty line).

`numeric_field` is not `required`, and of datatype `number`. This should evaluate correctly, emitting one row with `numeric_field`=`None`

**Comment by roll** [comment]
@pwalsh 
Could you check am I getting this right?

```
type = ConcreteJTSType(field)
type.cast(any-of-null-values-like-'')
if required:
  raise ConstraintError
else:
  return None
```

For example this test - https://github.com/frictionlessdata/jsontableschema-py/blob/master/tests/test_types.py#L636-L641 - not following this.

**Comment by pwalsh** [comment]
@roll what you describe is correct: if not required, then field can be any null value.

**Comment by roll** [comment]
And any null value is casting to `None`? 

Just to be sure because some tests have written otherwise (like '' should be converted to ''). I'll fix the tests and raise a PR so you both could check.

**Comment by pwalsh** [comment]
@roll i think so, yes. A few of us have touched this code now, but that is, I believe, the intention. I'd say a PR would be great so we can investigate.

**Comment by roll** [comment]
FIXED
