### ISSUE TITLE
Should maximum/minimum have the same fmt/pattern?

### ISSUE THREAD

**Issue by roll** [frictionlessdata/jsontableschema-py#67]
I suppose it's correct:
```
type: date
format: fmt:%Y
constraints:
  minimum: 2015
```

And it's not correct:
```
type: date
format: fmt:%Y
constraints:
  minimum: 2015-12-12
```

@rgrp It's not clear from spec.

**Comment by rgrp** [comment]
@roll good questions. IMO constraints should be always be ISO format and should always be yyyy-mm-dd so the latter in fact. worth opening on dataprotocols issue.

**Comment by roll** [comment]
MOVED TO SPEC
https://github.com/frictionlessdata/specs/issues/296
