### ISSUE TITLE
Remove types.NullType

### ISSUE THREAD

**Issue by roll** [frictionlessdata/jsontableschema-py#85]
# Overview

https://github.com/frictionlessdata/specs/issues/262

**Comment by pwalsh** [comment]
great. but also IIRC the null type is in fact used to fulfil some "missing value" functionality.

**Comment by roll** [comment]
Yes should be discovered.

**Comment by roll** [comment]
DUPLICATE
will be part of https://github.com/frictionlessdata/jsontableschema-py/issues/94
